### ISSUE TITLE
wont show

### ISSUE THREAD

**Issue by darkralts** [manu12121999/RemoveBG-GIMP#4]
on arch with gimp python and requests installed. pip install requests returns this
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests) (1.25.9)
it doesnt show up in the filters menu

**Comment by manu12121999** [comment]
I'm not sure about this but maybe you need python 2.7 or the file is not made executable. 
Otherwise, I don't know, sorry.

**Comment by darkralts** [comment]
I'll try both thanks! :D

**Comment by manu12121999** [comment]
Hi,
I think I found a solution for most linux systems. Check out the linux branch (make sure to download the file again, because it is slightly different from the master branch)

**Comment by manu12121999** [comment]
I changed the installation instructions and therefore closing the issue. If the plugin won't show up with the new method, feel free to reopen the issue.
